---
title: "EX01"
author: "이재서"
date: "2016년 7월 25일"
output: html_document
---
```{r}
#배열
array1 <- array(c(1:12), dim=c(4,3));array1
array2 <- array(c(1:12), dim=c(3,2,2));array2
```
  
실습문제(1)
```{r}
m <- array(c(1:8),dim=c(4,2));m
m[,1]
m[2,]
colnames(m) <- c('A','B');m
mm <- array(c(m,9:12), dim=c(4,3));mm
```

실습문제(2)
```{r}
n <- matrix(c(1:8), byrow=T, nrow=2);n
n[1,]
n[,4]
nn <- matrix(c(n,9:12), byrow=T, nrow=3);nn
colnames(nn) <- c("A","B","C","D");nn
matrix(c("J","A","V","A","C","A","F","E"), nrow=2, byrow=T)
```

실습문제(3)
```{r}
arr2 <- matrix(c("O","R","A","C","L","E","S","E","R","V","E","R"), byrow=T, nrow=2); arr2
arr2[1,3]
arr3 <- array(seq(15,90,5), dim=c(2,4,2)); arr3
arr3[,,2]
```

벡터로부터 데이터프레임 생성하기
```{r}
no <- c(1,2,3,4)
name <- c("Apple","Peach","Banana","Grape")
price <- c(500,200,100,50)
qty <- c(5,2,4,7)
sales <- data.frame(NO=no,NAME=name, PRICE=price, QTY=qty)
sales
sales$NAME
class(sales)
class(sales$NAME)
class(name)

#subset으로 원하는 조건만 조회
subset(sales, qty<5)
```

실습문제
```{r}
no <- c(1,2,3)
name <- c("apple","banana","peach")
price <- c(100,200,300)
df1 <- data.frame(NO=no, NAME=name, PRIcE=price);df1

no <- c(10,20,30)
name <- c("train","car","airplane")
price <- c(1000,2000,3000)
df2 <- data.frame(NO=no, NAME=name, PRIcE=price);df2
```

데이터프레임 합치기
```{r}
df3 <- cbind(df1,df2);df3
df4 <- rbind(df1,df2);df4
```

```{r}
df1 <- data.frame(name=c("apple","banana","cherry"), price=c(300,200,100))
df2 <- data.frame(name=c("apple","cherry","berry"),  qty=c(10,20,30))

merge(df1, df2)
merge(df1, df2, all=T)
cbind(df1, df2)
cbind(df2, df1)

new <- data.frame(name="mango", price=400)
df1 <- rbind(df1,new)
df1 <- rbind(df1, data.frame(name="berry", price=500))

df1 <- cbind(df1, data.frame(qty=c(10,20,30,40,50)))
```
특정 컬럼만 지정
```{r}
no <- c(1,2,3,4,5)
name <- c("서진수","주시현","최경우","이동근","윤정웅")
address <- c("서울","대전","포항","경주","경기")
tel <- c(1111,2222,3333,4444,5555)
hobby <- c("독서","미술","놀고먹기","먹고놀기","노는애감시하기")
member <- data.frame(NO=no,NAME=name,ADDRESS=address,TEL=tel,HOBBY=hobby)
member

#특정 컬럼만 지정
member2 <- subset(member,select=c(NO,NAME,TEL))
#특정 컬럼 제외
member3 <- subset(member, select=-TEL);member3
#열이름 변경하기
colnames(member3) <- c("번호","이름","주소","취미");member3
```

데이터프레임 내용확인
```{r}
ncol(member)
nrow(member)
names(member)
rownames(member);row.names(member)
colnames(member)
member[c(1,2,3,4,5),];member[c(4,2,1,1,5,3),]
member[c(1,2,3,4,5)];member[c(5,4,3,2,1)]
```

실습문제
```{r,warning=F}
s <- data.frame(name=c("김길동","강길동","박길동"), kor=c(100,90,85), mat=c(90,95,98), eng=c(80,98,100));s
colnames(s)
nrow(s)
s[c(1,2)]
s[c(1,3)]
s$name
subset(s,kor>=90)
subset(s,name=="박길동")
s <- rbind(s,data.frame(name="최길동",kor=80, mat=90, eng=93))
s
```

실습문제(2)
```{r, warning=F}
t <- data.frame(name=c("강길동","박길동","홍길동"), kor=c(90,85,92), mat=c(95,98,100))
t <- cbind(t,sci=c(95,100,94))
t[-2,]
t[-1]
t[c(1,4,2,3)]
```

실습문제(3)
```{r, warning=F}
merge(s,t)
merge(s,t,all=T)
t <- rbind(t,data.frame(name="최길동",kor=80, mat=90,sci=93))
cbind(s,t)
cbind(t,s)
tt <- t[c(1,2,3)]
ss <- s[c(1,2,3)]
rbind(tt,ss)
rbind(ss,tt)
```

디렉토리에 파일이름 확인하기
```{r}
list.files()
list.files(recursive=T)
list.files(all.files=T)
```
파일 불러오기
```{r}
setwd("c:\\r_temp")
scan1 <- scan('scan_1.txt')
scan2 <- scan('scan_2.txt')

##what=""를 써서 문자나 실수 불러오기
scan2 <- scan('scan_2.txt',what="")
scan3 <- scan('scan_3.txt',what="")
scan4 <- scan('scan_4.txt',what="")


input <- scan()##숫자입력
input2 <- scan(what="") ##문자입력
input3 <- readline() #한줄 입력하기
input4 <- readline("Are you OK? : ")
input5 <- readLines('scan_4.txt')

fruits <- read.table('fruits.txt', header=T)
fruits <- read.table('fruits.txt', header=T,nrow=2);fruits
fruit2 <- read.table('fruits_2.txt')
fruit2 <- read.table('fruits_2.txt',skip=2) ##2행부터
fruit2 <- read.table('fruits_2.txt',nrow=2) ##2개의 행만
fruit3 <- read.table('fruits.txt',header=T,nrow=2);fruit3
fruit3 <- read.table('fruits.txt',skip=2, nrow=2, col.names=c("no", "fruit","price","qty"));fruit3


label <- c("NO","NAME","PRIcE","QTY")
fruit4 <- read.csv('fruits_4.csv',header=F, col.names=label)

##read.csv(x)는 read.table(x,header=T, sep=",")이다
###여기서 sep="character"는 character를 기준으로 테이블 만들기
```

실습문제(1)
```{r, warning=F}
ch <- scan(what="")
mo <- scan()
num <- readline("Input Your number : ")
cs <- read.csv('csv_test.txt')
cs <- read.csv('csv_test.txt', header=T)
cs <- read.csv('csv_test.txt', header=F,skip=2, nrow=2)
```

```{r, warning=F}
ta <- read.table('table_test.txt')
ta <- read.table('table_test.txt', header=T, skip=2);ta
ta <- read.csv('csv_test.txt',skip=2,nrow=2, header=F)
ta[1]
ta[3]
ta[2]
ta <- rbind(ta,data.frame(V1=4, V2="포도", V3=4000))
```

xls파일로부터 데이터프레임 불러오기
```{r}
install.packages("XLConnect")
library(XLConnect)
data1 = loadWorkbook("fruits_6.xls",create=T)
data2 = readWorksheet(data1,sheet="sheet1",startRow=1, endRow=10, startCol=1, endCol=10)
```


기본함수들
```{r}
vec1 <- c(1,2,3,4,5)
vec2 <- c("A","B","C","D","E")
max(vec1);max(vec2)
mean(vec1);mean(vec2)
min(vec1);sd(vec1);sum(vec1);var(vec1)

install.packages("googleVis")
library(googleVis)
Fruits
#aggregate(계산될컬럼~기준될컬럼, 데이터, 계산식)
aggregate(Sales~Year, Fruits, sum)
aggregate(Sales~Fruit, Fruits, sum)
aggregate(Sales~Fruit+Year, Fruits, max)
aggregate(Sales+Expenses~Year, Fruits, max)

mat1 <- matrix(c(1,2,3,4,5,6), nrow=2, byrow=T);mat1
apply(mat1,1,sum)
apply(mat1,2,sum)
apply(mat1[,c(2,3)],2,max)

list1 <- list(Fruits$Sales)
list2 <- list(Fruits$Profit)
lapply(c(list1,list2),max)
sapply(c(list1,list2),max)
lapply(Fruits[,c(4,5)],max)
sapply(Fruits[,c(4,5)],max)


attach(Fruits)
tapply(Sales, Fruit, sum)
tapply(Sales,Year,sum)

vec1 <- c(1,2,3,4,5)
vec2 <- c(10,20,30,40,50)
vec3 <- c(100,200,300,400,500)
mapply(sum,vec1,vec2,vec3)

data1 <- read.csv('data1.csv')
sapply(data1[,-1],sum)
apply(data1,1,sum)
sapply(data1[c(1,2,3,4,5),],sum)
apply(data1[-1],1,sum)


##2번
class(data2)
data2 <- read.csv("1-4호선승하차승객수.csv")
attach(data2)
tapply(승차,노선번호,sum)
tapply(하차,노선번호,sum)
apply(data2[c(3,4)],2,sum)
aggregate(승차~노선번호, data2,sum)
colnames(data2)
aggregate(하차~노선번호, data2, sum)
aggregate(승차+하차~노선번호, data2, sum)

```

```{r}
x <- c(1,2,3,4)
log(x);log10(x);log2(x);log1p(x);
abs(1);abs(-1)
v3 <- c(1.2,1.8,2.1)
ceiling(v3)
floor(v3)
#이외에도 comsum, cumprod, cummax, cummin, sweep(데이터, 1:열/2:행, 빼고싶은 값벡터), gamma, exp, sqrt, factorial, 삼각함수등 여러 함수 사용가능하
```




